---
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: node
    static_configs:
      - targets:
          - cradle:9100
          - containerhost:9100
          - jenkins-master:9100
          - custodian:9100
          - bastion:9100

#     - tydus:9100
#     - weblb:9100
#     - upsilon-dev:9100
  - job_name: domain
    metrics_path: /probe
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: domain
      - target_label: __address__
        replacement: 10.88.0.1:9222
    static_configs:
      - targets:
          - diceapp.uk
          - dino-adventures.com
          - jamesandevie.com
          - jwread.com
          - technowax.net
          - jread.com
          - lanlist.co.uk
          - n64hub.org
          - redphase.info
          - teratan.net
          - upsilon-project.co.uk
          - upsilonproject.io
          - mogshots.io
          - wacky-tracky.com
          - wacky-tracky.co.uk
          - xconspirisist.co.uk
  - job_name: haproxy
    static_configs:
      - targets:
          - containerhost:8404
