---
- name: Install sysadmin packages
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora'
  ansible.builtin.package:
    state: present
    name:
      - vim-enhanced
      - vim-powerline
      - vim-command-t
      - vim-nerdtree
      - htop
      - vifm
