---
- name: install sysadmin packages
  package:
    state: present
    name:
      - vim-enhanced
      - vim-powerline
      - vim-command-t
      - vim-nerdtree
      - htop
      - vifm
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora'
