---
- name: GPG key - journalbeat
  ansible.builtin.rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Package - journalbeat
  ansible.builtin.package:
    name: https://artifacts.elastic.co/downloads/beats/journalbeat/journalbeat-7.11.1-x86_64.rpm

- name: Config - journalbeat
  ansible.builtin.copy:
    src: files/journalbeat.yml
    dest: /etc/journalbeat/journalbeat.yml
    mode: '0644'
  notify: restart - journalbeat

- name: Service - journalbeat
  ansible.builtin.systemd_service:
    name: journalbeat
    state: started
    masked: false
