---
- name: Skip host if it's a VM
  ansible.builtin.meta: end_host
  when: ansible_virtualization_role == "guest"

- name: Install ethtool
  ansible.builtin.package:
    name: ethtool
    state: installed

- name: Copy wol script
  ansible.builtin.copy:
    src: wol
    dest: /usr/bin/wol-enable
    mode: '0755'

- name: Run wol script
  ansible.builtin.command: /usr/bin/wol-enable
  register: output
  changed_when: output.rc != 0

- name: Copy systemd unit
  ansible.builtin.copy:
    src: wol.service
    dest: /etc/systemd/system/
    mode: '0644'

- name: Enable wol service
  ansible.builtin.systemd_service:
    name: wol
    daemon_reload: true
    state: started
    enabled: true
