---
- name: Skip host if it's a VM
  ansible.builtin.meta: end_host
  when: ansible_virtualization_role == "guest"

- name: Install ethtool
  ansible.builtin.package:
    name: ethtool
    state: installed

- name: Copy wol script
  ansible.builtin.copy:
    src: wol
    dest: /etc/init.d/
    mode: '0644'

- name: Enable wol service
  ansible.builtin.service:
    name: wol
    enabled: true
