- name: mkdir /etc/prometheus
  file:
    path: /etc/prometheus
    state: directory
    mode: 0755

- name: prometheus - set config
  tags: prom
  ansible.builtin.template:
    src: "{{ cfg_file }}"
    dest: /etc/prometheus/prometheus.yml
  notify: container prometheus restart

- name: prometheus - define container
  tags: prom
  containers.podman.podman_container:
    name: prometheus
    image: prom/prometheus
    state: started
    privileged: yes
    security_opt: label=disable
    volume: /etc/prometheus/:/etc/prometheus
    user: root
    ports: 
      - "9090:9090"

