---
- name: Make directory /etc/prometheus
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    mode: '0755'

- name: Prometheus - set config
  tags: prom
  ansible.builtin.template:
    src: '{{ cfg_file }}'
    dest: /etc/prometheus/prometheus.yml
    mode: '0644'
  notify: Container prometheus reload config

- name: Prometheus - set alert rules
  tags: prom
  ansible.builtin.copy:
    src: '{{ alert_file }}'
    dest: /etc/prometheus/alert.rules
    mode: '0644'
  notify: Container prometheus reload config

- name: Prometheus - define container
  tags: prom
  containers.podman.podman_container:
    name: prometheus
    image: docker.io/prom/prometheus
    state: started
    privileged: true
    conmon_pidfile: /etc/prometheus/prometheus.pid
    security_opt: label=disable
    volume: /etc/prometheus/:/etc/prometheus
    user: root
    ports:
      - 9090:9090
