---
- name: Make directory /etc/prometheus
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    mode: '0755'

- name: Prometheus - set config
  tags: prom
  ansible.builtin.template:
    src: '{{ cfg_file }}'
    dest: /etc/prometheus/prometheus.yml
    mode: '0644'
  notify: Container prometheus reload config

- name: Prometheus - set alert rules
  tags: prom
  ansible.builtin.copy:
    src: '{{ alert_file }}'
    dest: /etc/prometheus/alert.rules
    mode: '0644'
  notify: Container prometheus reload config

- name: Prometheus - copy quadlet
  tags: prom
  ansible.builtin.copy:
    src: 'prometheus.container'
    dest: /etc/containers/systemd/prometheus.container
    mode: '0600'
  notify: Container prometheus reload config

- name: Start Prometheus
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: true
  tags: prom
