---
- name: Package - httpd, php
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  with_items:
    - httpd
    - php

- name: Service - httpd
  ansible.builtin.service:
    name: httpd
    enabled: 'yes'
    state: started

- name: Firewall - enable httpd
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled

- name: Service - firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted
