---
namespace: jamesread
name: soe
description: A standard operating environment collection.
version: 4.4.2
readme: README.md

authors:
  - James Read <contact@jread.com>

dependencies:
  containers.podman: ">=1.10.1"

license:
  - GPL-3.0-or-later

tags:
  - linux
  - podman
  - systemd

repository: https://github.com/jamesread/jwr-soe-ansible
documentation: https://github.com/jamesread/jwr-soe-ansible
homepage: https://github.com/jamesread/jwr-soe-ansible
issues: https://github.com/jamesread/jwr-soe-ansible/issues
