---
- name: Container - traefik - config
  ansible.builtin.copy:
    src: '{{ traefik_config }}'
    dest: '{{ traefik_volume }}/apps.json'
    mode: '0644'
  notify: Container traefik restart

- name: Container - traefik
  tags: traefik
  containers.podman.podman_container:
    name: traefik
    image: traefik:latest
    state: started
    privileged: true
    security_opt: label=disable
    user: root
    volume: '{{ traefik_volume }}/:/app/data/'
    ports:
      - 8383:8080
