---
- name: Generate cloud-init
  ansible.builtin.template:
    src: cloudinit.j2
    dest: /tmp/meta-data
    mode: '0644'

- name: Generate user-data
  ansible.builtin.template:
    src: user-data.j2
    dest: /tmp/user-data
    mode: '0644'
  notify: Genisoimage
