---
- name: Make directory config
  ansible.builtin.file:
    path: /etc/prometheus-gmail-exporter
    state: directory
    mode: '0755'

- name: Template - secret file
  ansible.builtin.template:
    src: '{{ secret_file }}'
    dest: /etc/prometheus-gmail-exporter/client_secret.json
    mode: '0644'

- name: Template - config file
  ansible.builtin.template:
    src: '{{ config_file }}'
    dest: /etc/prometheus-gmail-exporter/prometheus-gmail-exporter.cfg
    mode: '0644'

- name: Prometheus - define container
  containers.podman.podman_container:
    name: prometheus-gmail-exporter
    image: jamesread/prometheus-gmail-exporter
    state: started
    privileged: true
    recreate: true
    force_restart: true
    security_opt: label=disable
    volume: /etc/prometheus-gmail-exporter/:/root/.prometheus-gmail-exporter/
    user: root
    ports:
      - 8082:8080
