- name: container - grafana
  containers.podman.podman_container:
    name: grafana
    image: grafana/grafana
    state: started
    privileged: yes
    security_opt: "label=disable"
    volume: "{{ container_podman_volume }}/:/var/lib/grafana/:Z"
    user: root
    ports:
      - "3000:3000"
