- package: 
    name: 
      - libvirt
      - libvirt-client
      - libguestfs
      - qemu-device-display-qxl
      - qemu-device-usb-redirect
      - qemu-ui-spice-app
    state: installed

- service:
    name: libvirtd
    state: started
    enabled: yes

