---
- name: Jenkins repo
  ansible.builtin.yum_repository:
    name: jenkins
    baseurl: http://pkg.jenkins.io/redhat
    gpgcheck: false
    enabled: true
    description: Jenkins

- name: Package - jenkins and lots of stuff
  ansible.builtin.package:
    state: present
    name:
      - zip
      - httpd
      - jenkins
      - java
      - pytest
      - make
      - autoconf
      - php
      - php-phpunit-PHPUnit
      - ant
      - maven
      - java
      - puppet
      - rubygem-puppet-lint
      - composer
      - cmake
      - mariadb-server
      - mariadb
      - rpm-build

- name: Jenkins config
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/jenkins
    regexp: ^JENKINS_ARGS=
    line: 'JENKINS_ARGS="--prefix=/jenkins" '
    state: present

- name: Find initial admin password file
  ansible.builtin.stat:
    path: /var/lib/jenkins/secrets/initialAdminPassword
  register: inital_admin_password_file

- name: Get initial admin password
  ansible.builtin.set_fact:
    admin_password: "{{ lookup('file', '/var/lib/jenkins/secrets/initialAdminPassword') }}"
  when: inital_admin_password_file.stat.exists

- name: Admin Password
  ansible.builtin.debug:
    msg: '{{ admin_password }}'
  when: inital_admin_password_file.stat.exists

- name: Copy proxy conf to httpd
  ansible.builtin.copy:
    src: jenkins-proxy.conf
    dest: /etc/httpd/conf.d/jenkins-proxy.conf
    mode: '0644'

- name: Copy index.htm
  ansible.builtin.copy:
    src: index.htm
    dest: /var/www/html/index.html
    mode: '0644'

- name: SElinux - httpd_can_network_connect
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true

- name: Service start {{ item }}
  ansible.builtin.service:
    name: '{{ item }}'
    state: started
  with_items:
    - httpd
    - jenkins
    - mariadb

- name: Firewall rule - node-exporter
  ansible.posix.firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled
