- name: package - haproxy
  package:
    name: haproxy
    state: present

- name: sebool - haproxy
  tags: haproxy
  ansible.posix.seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes
    ignore_selinux_state: yes

- name: template - haproxy
  tags: haproxy
  template:
    src: "{{ haproxy_cfg_file }}"
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  notify:
    - service haproxy restart

- name: service - haproxy
  tags: haproxy
  service: 
    name: haproxy
    state: started
    enabled: yes
