---
- name: Package - haproxy
  ansible.builtin.package:
    name: haproxy
    state: present

- name: SEbool - haproxy
  tags: haproxy
  ansible.posix.seboolean:
    name: haproxy_connect_any
    state: true
    persistent: true
    ignore_selinux_state: true

- name: Template - haproxy
  tags: haproxy
  ansible.builtin.template:
    src: '{{ cfg_file }}'
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify:
    - Service haproxy restart

- name: Service - haproxy
  tags: haproxy
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: true
