---
galaxy_info:
  author: jamesread
  description: Install i3wm.
  license: GPL-3.0-or-later
  min_ansible_version: "2.7"
  platforms:
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - kubernetes
