---
galaxy_info:
  role_name: machine_jenkins_slave
  author: jamesread
  description: Installs a Jenkins slave.
  license: GPL-3.0-or-later
  min_ansible_version: 2.7
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
