---
galaxy_info:
  author: jamesread
  description: Installs a journalbeat systemd service.
  license: GPL-3.0-or-later
  min_ansible_version: "2.7"
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - podman
    - fedora
