---
galaxy_info:
  author: jamesread
  description: My heads up display (kiosk)
  license: GPL-3.0-or-later
  min_ansible_version: "2.7"
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - fedora
    - kiosk
