---
- name: Packages - uninstall junk
  ansible.builtin.package:
    name: '{{ item }}'
    state: absent
  with_items:
    - xscreensaver
    - fluxbox
  when: ansible_distribution == "debian"

- name: Packages - install essentials
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  with_items:
    - unclutter

- name: Copy lxde config
  ansible.builtin.copy:
    src: lxde-autostart
    dest: /home/pi/.config/lxsession/LXDE/autostart
    mode: '0644'

- name: Copy fluxbox config
  ansible.builtin.copy:
    src: fluxbox-startup
    dest: /home/pi/.fluxbox/startup
    mode: '0644'

- name: Copy xinitrc
  ansible.builtin.copy:
    src: xinitrc
    dest: /home/pi/.xinitrc
    mode: '0644'

- name: Copy lightdm conf
  ansible.builtin.copy:
    src: lightdm.conf
    dest: /etc/lightdm/lightdm.conf
    mode: '0644'
