---
galaxy_info:
  role_name: container_openhab
  author: jamesread
  description: Installs a OpenHAB container.
  license: GPL-3.0-or-later
  min_ansible_version: '2.7'
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - podman
