---
- name: Packages - kvm, etc
  ansible.builtin.package: name={{ item }} state=present
  with_items:
    - libvirt
    - libvirt-client
    - libguestfs
    - virt-install
    - bridge-utils
    - qemu-kvm
    - qemu-img
    - qemu-system-x86
    - qemu-device-display-qxl
    - qemu-device-usb-redirect
    - qemu-ui-spice-app

- name: Service - libvirtd
  ansible.builtin.service:
    name: libvirtd
    state: started
    enabled: 'yes'
