---
- name: Install base packages
  ansible.builtin.package:
    name:
      - firewalld
      - vim-enhanced
        #      - elinks
      - git
      - wget
      - unzip
      - psmisc
      - smartmontools
    state: present

- name: Debug - print pkr_mgr
  ansible.builtin.debug:
    msg: '{{ ansible_facts.pkg_mgr }}'

- name: Package - libsemanage for SELinux systems
  ansible.builtin.package:
    name: python3-libsemanage
    state: present
  when: ansible_facts.pkg_mgr == 'dnf'

- name: Install copr for YUM based systems
  ansible.builtin.package:
    name: yum-plugin-copr
  when: ansible_facts.pkg_mgr == 'yum'
  tags: copr

- name: Enable prometheus repo -copr
  community.general.copr:
    state: enabled
    name: ibotty/prometheus-exporters
  tags: copr
