---
- name: Install base packages
  ansible.builtin.package:
    name:
      - firewalld
      - vim-enhanced
        #      - elinks
      - git
      - wget
      - unzip
      - psmisc
      - smartmontools
      - python3-libsemanage
    state: present
