---
- name: Include Red Hat Tasks
  ansible.builtin.include_tasks:
    file: family_rh.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora'

- name: Include Debian Tasks
  ansible.builtin.include_tasks:
    file: family_deb.yml
  when: ansible_distribution == 'Debian'

- name: Install IP Address issue file
  ansible.builtin.copy:
    src: ipaddress.issue
    dest: /etc/issue.d/
    mode: '0644'

  # Start NTP
  # - service: name={{ item }} state=started enabled=yes
  #  name: start essential services
  #  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora'
  #  with_items:
  #    - ntpd

- name: Install podman
  ansible.builtin.include_role:
    name: jamesread.soe.machine_podman

- name: Install systemd-exporter
  containers.podman.podman_container:
    name: systemd-exporter
    image: quay.io/prometheuscommunity/systemd-exporter:latest
    state: started
    ports:
      - "9558:9558"
  tags: systemd-exporter

- name: Firewall rule - systemd-exporter
  ansible.posix.firewalld:
    port: 9558/tcp
    permanent: true
    state: enabled
  tags: systemd-exporter

- name: Firewall rule - node-exporter
  ansible.posix.firewalld:
    port: 9100/tcp
    permanent: true
    state: enabled
  tags: node-exporter

- name: Package - node-exporter
  ansible.builtin.package:
    name: node_exporter
    state: latest
  tags: node-exporter

- name: Service - node-exporter
  ansible.builtin.service:
    name: node_exporter
    state: started
    enabled: true
  tags: node-exporter

- name: Copy script - prom smartmon
  ansible.builtin.copy:
    src: files/prometheus_smartmon.sh
    dest: /usr/local/sbin/prometheus_smartmon.sh
    mode: '0755'
  tags: node-exporter

- name: Smart timer
  ansible.builtin.copy:
    src: files/prometheus_smartmon.timer
    dest: /etc/systemd/system/prometheus_smartmon.timer
    mode: '0644'
  tags: node-exporter

- name: Smart service
  ansible.builtin.copy:
    src: files/prometheus_smartmon.service
    dest: /etc/systemd/system/prometheus_smartmon.service
    mode: '0644'
  tags: node-exporter

- name: Systemd daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true
  tags: node-exporter

- name: Enable Smartmon Timer in systemd
  ansible.builtin.systemd_service:
    name: prometheus_smartmon.timer
    state: started
    enabled: true
  tags: node-exporter

- name: Update the /etc/ssh/sshd_config file
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^UseDNS
    line: UseDNS no
    insertafter: EOF
    state: present
  notify: Restart ssh
