---
- name: Make directory config
  ansible.builtin.file:
    path: /etc/prom-gcal-exporter
    state: directory
    mode: '0755'

- name: Template - secret file
  ansible.builtin.template:
    src: '{{ secret_file }}'
    dest: /etc/prom-gcal-exporter/client_secret.json
    mode: '0644'

- name: Tempplate - config file
  ansible.builtin.template:
    src: '{{ config_file }}'
    dest: /etc/prom-gcal-exporter/prometheus-gcal-exporter.cfg
    mode: '0644'

- name: Define container prometheus
  containers.podman.podman_container:
    name: prom-gcal-exporter
    image: jamesread/prometheus-google-calendar-exporter
    state: started
    privileged: true
    recreate: true
    force_restart: true
    security_opt: label=disable
    volume: /etc/prom-gcal-exporter/:/root/.prometheus-gcal-exporter/
    user: root
    ports:
      - 8081:8080
