---
- name: Container - elasticsearch
  containers.podman.podman_container:
    name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    env:
      discovery.type: single-node
      ELASTIC_PASSWORD: changeme
    state: started
    user: root
    ports:
      - 9200:9200
      - 9300:9300

- name: File - fluentd.conf
  ansible.builtin.copy:
    src: fluentd.conf
    dest: /etc/fluentd.conf
    mode: '0644'

- name: File - kibana.yml
  ansible.builtin.copy:
    src: kibana.yml
    dest: /etc/kibana.yml
    mode: '0644'

- name: Container - kibana
  containers.podman.podman_container:
    image: docker.elastic.co/kibana/kibana:7.11.0
    name: kibana
    ports:
      - 5601:5601
    env:
      discovery.type: single-node
      ELASTIC_PASSWORD: changeme
    volumes:
      - /etc/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
