---
- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
  register: selinux

- name: Trigger reboot
  when: selinux.changed
  block:
    - reboot:

- name: Enable CRIO Module
  shell: dnf module enable cri-o:1.24 -y

- name: Check if crio is installed
  stat:
    path: /usr/bin/crio
  register: crio

- name: Install CIO
  when: not crio.stat.exists
  block:
    - shell: dnf module enable cri-o:1.24 -y
    - package:
        name:
          - cri-o
          - crictl
          - ethtool
          - kubernetes-node
          - kubernetes-client
          - kubernetes-kubeadm
          - nfs-utils
          - iptables-nft
          - iproute-tc
        state: installed
      tags: k8s_packages
    - package:
        name:
          - firewalld
          - zram-generator
        state: removed
      tags: k8s_packages

- name: Replace kubeadm.conf because of messed up fedora package still using --cni*
  copy:
    dest: /etc/systemd/system/kubelet.service.d/kubeadm.conf
    src: kubeadm.conf
  tags: kubeadm.conf

- name: Copy k8s modprobe
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    src: files/k8s-modprobe.conf

- modprobe:
    name: br_netfilter
    state: present

- ansible.builtin.service:
    name: crio
    state: started
    enabled: true

- ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present

- ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present

- ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present

- ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    state: present

- service:
    name: kubelet
    daemon_reload: true
    enabled: true
    state: started
  tags: kubelet

- service:
    name: systemd-resolved
    enabled: false
    state: stopped
  tags: resolved

- name: Reboot because of systemd-resolved disable
  reboot:

- name: remove old systemd-resolved resolv.conf stub
  file:
    path: /etc/resolv.conf
    state: absent

- name: restart network manager to regenerate resolv.conf
  service:
    name: NetworkManager
    state: restarted
    enabled: true
  tags: NM

- name: Reboot because of network manager
  reboot:

- name: Kubeadm pull
  shell: kubeadm config images pull
  tags: kubeadm-pull
