---
- name: Disable SELinux
  ansible.posix.selinux: 
    state: disabled 
  register: selinux

- when: selinux.changed
  block:
    - reboot:

- shell: dnf module enable cri-o:1.24 -y

- name: check if crio is installed
  stat:
    path: /usr/bin/crio
  register: crio

- when: not crio.stat.exists
  block:
  - shell: dnf module enable cri-o:1.24 -y

  - package: 
      name: 
        - cri-o
        - crictl 
        - ethtool
        - kubernetes-node
        - kubernetes-client
        - kubernetes-kubeadm
        - nfs-utils
        - iptables-nft
        - iproute-tc
      state: installed
    tags: k8s_packages

  - package:
      name:
        - firewalld
        - zram-generator
      state: removed
    tags: k8s_packages

- name: replace kubeadm.conf because of messed up fedora package still using --cni*
  copy:
    dest: /etc/systemd/system/kubelet.service.d/kubeadm.conf
    src: kubeadm.conf
  tags: kubeadm.conf

- name: copy k8s modprobe
  copy:
    dest: /etc/modules-load.d/k8s.conf
    src: files/k8s-modprobe.conf

- modprobe:
    name: br_netfilter
    state: present

- service:
    name: crio
    state: started
    enabled: yes

- ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present

- ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present

- ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present

- ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    state: present

- service:
    name: kubelet
    daemon_reload: yes
    enabled: yes
    state: started
  tags: kubelet

- service:
    name: systemd-resolved
    enabled: no
    state: stopped
  tags: resolved

- reboot:

- name: remove old systemd-resolved resolv.conf stub
  file:
    path: /etc/resolv.conf
    state: absent

- name: restart network manager to regenerate resolv.conf
  service:
    name: NetworkManager
    state: restarted
    enabled: yes
  tags: NM

- reboot:

- shell: kubeadm config images pull
  tags: kubeadm-pull

