---
- name: Config - promtail dir
  ansible.builtin.file:
    path: /etc/promtail/
    state: directory
    mode: '0644'

- name: Config - promtail
  ansible.builtin.copy:
    src: files/promtail.yml
    dest: /etc/promtail/config.yml
    mode: '0644'

- name: Container - promtail
  containers.podman.podman_container:
    name: promtail
    image: grafana/promtail
    state: started
    privileged: true
    user: root
    volumes:
      - /etc/promtail/:/etc/promtail/:ro
      - /var/log/journal/:/mnt:ro
