---
galaxy_info:
  author: jamesread
  description: Installs jenkins as a service.
  license: GPLv3
  min_ansible_version: 2.7
  platforms:
    - name: CentOS
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - jenkins
