---
galaxy_info:
  author: jamesread
  description: Installs httpd.
  license: GPLv3
  min_ansible_version: '2.7'
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - httpd
