name: build and publish tag

on: # yamllint disable-line
  workflow_dispatch:
  push:
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish Ansible Galaxy Collection
        uses: buluma/ansible_galaxy_collection@v2.7.2
        with:
          api_key: '${{ secrets.GALAXY_API_KEY }}'
          galaxy_version: '${{ github.ref_name }}'
